package GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aitd.module_chat.ui.emotion.db.Sticker;
import com.aitd.module_chat.ui.emotion.db.TBCollection;
import com.aitd.module_chat.ui.emotion.db.TBRecord;

import GreenDao.StickerDao;
import GreenDao.TBCollectionDao;
import GreenDao.TBRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stickerDaoConfig;
    private final DaoConfig tBCollectionDaoConfig;
    private final DaoConfig tBRecordDaoConfig;

    private final StickerDao stickerDao;
    private final TBCollectionDao tBCollectionDao;
    private final TBRecordDao tBRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stickerDaoConfig = daoConfigMap.get(StickerDao.class).clone();
        stickerDaoConfig.initIdentityScope(type);

        tBCollectionDaoConfig = daoConfigMap.get(TBCollectionDao.class).clone();
        tBCollectionDaoConfig.initIdentityScope(type);

        tBRecordDaoConfig = daoConfigMap.get(TBRecordDao.class).clone();
        tBRecordDaoConfig.initIdentityScope(type);

        stickerDao = new StickerDao(stickerDaoConfig, this);
        tBCollectionDao = new TBCollectionDao(tBCollectionDaoConfig, this);
        tBRecordDao = new TBRecordDao(tBRecordDaoConfig, this);

        registerDao(Sticker.class, stickerDao);
        registerDao(TBCollection.class, tBCollectionDao);
        registerDao(TBRecord.class, tBRecordDao);
    }
    
    public void clear() {
        stickerDaoConfig.clearIdentityScope();
        tBCollectionDaoConfig.clearIdentityScope();
        tBRecordDaoConfig.clearIdentityScope();
    }

    public StickerDao getStickerDao() {
        return stickerDao;
    }

    public TBCollectionDao getTBCollectionDao() {
        return tBCollectionDao;
    }

    public TBRecordDao getTBRecordDao() {
        return tBRecordDao;
    }

}
