package GreenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.aitd.module_chat.ui.emotion.db.Sticker;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STICKER".
*/
public class StickerDao extends AbstractDao<Sticker, Long> {

    public static final String TABLENAME = "STICKER";

    /**
     * Properties of entity Sticker.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property LocalPath = new Property(2, String.class, "localPath", false, "LOCAL_PATH");
        public final static Property OriginUrl = new Property(3, String.class, "originUrl", false, "ORIGIN_URL");
        public final static Property Width = new Property(4, int.class, "width", false, "WIDTH");
        public final static Property Height = new Property(5, int.class, "height", false, "HEIGHT");
        public final static Property Index = new Property(6, int.class, "index", false, "INDEX");
        public final static Property Belong = new Property(7, String.class, "belong", false, "BELONG");
    }


    public StickerDao(DaoConfig config) {
        super(config);
    }
    
    public StickerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STICKER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"LOCAL_PATH\" TEXT," + // 2: localPath
                "\"ORIGIN_URL\" TEXT," + // 3: originUrl
                "\"WIDTH\" INTEGER NOT NULL ," + // 4: width
                "\"HEIGHT\" INTEGER NOT NULL ," + // 5: height
                "\"INDEX\" INTEGER NOT NULL ," + // 6: index
                "\"BELONG\" TEXT);"); // 7: belong
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STICKER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sticker entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(3, localPath);
        }
 
        String originUrl = entity.getOriginUrl();
        if (originUrl != null) {
            stmt.bindString(4, originUrl);
        }
        stmt.bindLong(5, entity.getWidth());
        stmt.bindLong(6, entity.getHeight());
        stmt.bindLong(7, entity.getIndex());
 
        String belong = entity.getBelong();
        if (belong != null) {
            stmt.bindString(8, belong);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sticker entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String localPath = entity.getLocalPath();
        if (localPath != null) {
            stmt.bindString(3, localPath);
        }
 
        String originUrl = entity.getOriginUrl();
        if (originUrl != null) {
            stmt.bindString(4, originUrl);
        }
        stmt.bindLong(5, entity.getWidth());
        stmt.bindLong(6, entity.getHeight());
        stmt.bindLong(7, entity.getIndex());
 
        String belong = entity.getBelong();
        if (belong != null) {
            stmt.bindString(8, belong);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sticker readEntity(Cursor cursor, int offset) {
        Sticker entity = new Sticker( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // localPath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // originUrl
            cursor.getInt(offset + 4), // width
            cursor.getInt(offset + 5), // height
            cursor.getInt(offset + 6), // index
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // belong
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sticker entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocalPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOriginUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWidth(cursor.getInt(offset + 4));
        entity.setHeight(cursor.getInt(offset + 5));
        entity.setIndex(cursor.getInt(offset + 6));
        entity.setBelong(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sticker entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sticker entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sticker entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
